DROP TABLE IF EXISTS consultor_projeto
DROP TABLE IF EXISTS projeto
DROP TABLE IF EXISTS consultor
DROP TABLE IF EXISTS empresa
DROP TABLE IF EXISTS endereco

USE master

ALTER DATABASE DB_EMPRESA SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DROP DATABASE IF EXISTS DB_EMPRESA